version: '3.3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - '5002:80'
    depends_on:
      - db
    networks:
      shortner_net:
        ipv4_address: 172.28.0.8  
  management-app:
    build: ./managmentService_url
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
    restart: always
    ports:
      - 4444:4444
    networks:
      shortner_net:
        ipv4_address: 172.28.0.7
  redirect-app:
    build: ./redirectionService_url
    depends_on:
      - redis
    restart: always
    ports:
      - 2222:2222
    networks:
      shortner_net:
        ipv4_address: 172.28.0.9      
  db:
    build: ./managmentService_url/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: management_service
      MYSQL_USER: userOne
      MYSQL_PASSWORD: test123
    networks:
      shortner_net:
        ipv4_address: 172.28.0.6
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    networks:
      shortner_net:
        ipv4_address: 172.28.0.5
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672      
    networks:
      shortner_net:
        ipv4_address: 172.28.0.4
networks:
  shortner_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
